from __future__ import annotations

from dataclasses import dataclass

import numpy as np


@dataclass
class BodyState:
    """Simple position/velocity state for numerical integration."""

    pos: np.ndarray
    vel: np.ndarray


class UAVDynamics:
    """
    Small quadcopter-like translational dynamics.

    The true trajectory is generated by numerically integrating a commanded
    acceleration that tracks a smooth reference trajectory.
    """

    def __init__(self, cfg):
        self.cfg = cfg
        self.gravity = np.array([0.0, 0.0, -cfg.GRAVITY], dtype=float)

        # PD tracking gains for the simulated vehicle.
        self.kp = 60.0
        self.kd = 15.0
        self.max_acc = 6.0

    def command_accel(
        self,
        p_ref: np.ndarray,
        v_ref: np.ndarray,
        a_ref: np.ndarray,
        p: np.ndarray,
        v: np.ndarray,
    ) -> np.ndarray:
        """Feedforward + feedback acceleration command."""
        a_cmd = a_ref + self.kp * (p_ref - p) + self.kd * (v_ref - v)
        return np.clip(a_cmd, -self.max_acc, self.max_acc)

    def integrate(
        self,
        p: np.ndarray,
        v: np.ndarray,
        a: np.ndarray,
        dt: float,
    ) -> tuple[np.ndarray, np.ndarray]:
        """Second-order kinematic integration."""
        p_new = p + v * dt + 0.5 * a * dt * dt
        v_new = v + a * dt
        return p_new, v_new